# Generated by Django 5.2.11 on 2026-02-03 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('lighthouse', '0001_lighthouse_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='crontab',
            field=models.ForeignKey(blank=True, help_text='Расписание запуска задачи по crontab.\n!!! Один из interval или crontab должен быть задан. Если заданы оба, приоритет будет у interval.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.crontabschedule'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='interval',
            field=models.ForeignKey(blank=True, help_text='Интервал запуска задачи.\n!!! Один из interval или crontab должен быть задан. Если заданы оба, приоритет будет у interval.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.intervalschedule'),
        ),
    ]
