# Generated by Django 5.2.11 on 2026-02-03 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('lighthouse', '0003_alter_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='crontab',
            field=models.ForeignKey(blank=True, help_text='Расписание запуска задачи по crontab.\n\n\nОдин из interval или crontab должен быть задан. Если заданы оба, приоритет будет у interval.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.crontabschedule'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='interval',
            field=models.ForeignKey(blank=True, help_text='Интервал запуска задачи.\n\n\nОдин из interval или crontab должен быть задан. Если заданы оба, приоритет будет у interval.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.intervalschedule'),
        ),
        migrations.AlterField(
            model_name='source',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='headers',
            field=models.JSONField(default='null', help_text='Произвольные заголовки для запроса Lighthouse.Формат: {"Header-Name": "Header Value"}Ecсли заголовки не нужны, оставить null.'),
        ),
        migrations.AlterField(
            model_name='source',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Произвольные метаданные для ELK (например project, page_type).Формат: {"key1": "value1", "key2": "value2"}', null=True),
        ),
    ]
