# Generated by Django 5.2.11 on 2026-02-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0004_alter_checklistitem_crontab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='metadata',
            field=models.JSONField(blank=True, default='"project" : "not set""page_type" : "not set"', help_text='Произвольные метаданные для ELK (например project, page_type).Формат: {"key1": "value1", "key2": "value2"}', null=True),
        ),
    ]
