# Generated by Django 5.2.11 on 2026-02-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0005_alter_source_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='metadata',
            field=models.JSONField(blank=True, default='\n            {\n                "project": "not set",\n                "page_type": "not set"\n            }\n            ', help_text='Произвольные метаданные для ELK (например project, page_type).Формат: {"key1": "value1", "key2": "value2"}', null=True),
        ),
    ]
