# Generated by Django 5.2.11 on 2026-02-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0006_alter_source_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='headers',
            field=models.JSONField(blank=True, default=None, help_text='Произвольные заголовки для запроса Lighthouse.Формат: {"Header-Name": "Header Value"}Ecсли заголовки не нужны, оставить null.', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='metadata',
            field=models.JSONField(blank=True, default={'page_type': 'not set', 'project': 'not set'}, help_text='Произвольные метаданные для ELK (например project, page_type).Формат: {"key1": "value1", "key2": "value2"}', null=True),
        ),
    ]
