# Generated by Django 5.2.11 on 2026-02-03 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0007_alter_source_headers_alter_source_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 3, 20, 44, 14, 60529, tzinfo=datetime.timezone.utc), help_text='Время запуска задачи. (по стандарту через 5 минут от текущего времени)'),
        ),
    ]
