# Generated by Django 5.2.11 on 2026-02-05 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0027_alter_checklistitem_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 5, 10, 35, 11, 479007, tzinfo=datetime.timezone.utc), help_text='Время запуска задачи. (по стандарту через 5 минут от текущего времени)'),
        ),
    ]
