# Generated by Django 6.0.1 on 2026-01-27 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CheckListItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='check_list.dashboard')),
            ],
        ),
    ]
