# Generated by Django 5.2.10 on 2026-01-27 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_list', '0001_initial'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='scheduled_time',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='interval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.intervalschedule'),
        ),
    ]
