# Generated by Django 5.2.10 on 2026-01-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_list', '0003_add_missing_fields_and_checkevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkevents',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='time_for_check',
            field=models.IntegerField(help_text='Время в минутах для проверки дашборда'),
        ),
    ]
