# Generated by Django 5.2.10 on 2026-01-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_list', '0004_alter_checkevents_uuid_alter_dashboard_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
