# Generated by Django 5.2.10 on 2026-01-28 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_list', '0005_alter_checklistitem_description'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkevents',
            name='problem',
        ),
        migrations.AddField(
            model_name='checkevents',
            name='no_problem',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='crontab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.crontabschedule'),
        ),
    ]
