# Generated by Django 5.2.11 on 2026-02-03 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_list', '0006_remove_checkevents_problem_checkevents_no_problem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='checkevents',
            name='dash_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='check_list.dashtype'),
        ),
    ]
