# Generated by Django 5.2.11 on 2026-02-03 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_list', '0007_dashtype_checkevents_dash_type'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='crontab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_list_crontab_items', to='django_celery_beat.crontabschedule'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='interval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_list_interval_items', to='django_celery_beat.intervalschedule'),
        ),
    ]
