# Generated by Django 5.2.11 on 2026-02-05 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_list', '0035_alter_checklistitem_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='description',
            field=models.TextField(blank=True, help_text='Описание задачи для проверки дашборда.\nМожно писать в Telegram MarkdownV2 формате. \n```блок кода``` \n`код` \n*жирный* \n_курсив_ \n__подчёркнутый__ \n~зачёркнутый~ \n[ссылка](http://example.com) \n\n%без форматирования%', null=True),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 5, 11, 39, 30, 343836, tzinfo=datetime.timezone.utc), help_text='Время запуска задачи. (по стандарту через 5 минут от текущего времени)'),
        ),
    ]
