# Generated by Django 5.2.10 on 2026-02-05 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_list', '0039_alter_checklistitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 5, 14, 7, 21, 105517, tzinfo=datetime.timezone.utc), help_text='Время запуска задачи. (по стандарту через 5 минут от текущего времени)'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
